<?php

/**
 * BordereauTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BordereauTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BordereauTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bordereau');
    }
}