<?php

/**
 * ClasseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClasseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClasseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Classe');
    }
}