<?php

/**
 * CommandeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommandeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommandeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Commande');
    }
}