<?php

/**
 * FactureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FactureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FactureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Facture');
    }
}