<?php

/**
 * Facture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Facture extends BaseFacture
{
	public function init($user,$userModif,$idClient,$totalHT,$totalTTC){
        $this->IdUser = $user;
        $this->IdUserModif = $userModif;
        $this->IdClient =$idClient;
        $this->TotalHT =$totalHT;
        $this->TotalTTC =$totalTTC;
   }

}