<?php

/**
 * FournisseurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FournisseurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FournisseurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fournisseur');
    }
}