<?php

/**
 * Fournisseur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fournisseur extends BaseFournisseur
{

    public function init($libelle, $adresse, $tel, $mail, $commentaire){
        $this->Libelle =$libelle;
        $this->Adresse =$adresse;
        $this->Mail =$mail;
        $this->Tel =$tel;
        $this->Commentaire =$commentaire;
    }
}