<?php

/**
 * FournisseurProduitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FournisseurProduitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FournisseurProduitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FournisseurProduit');
    }
}