<?php

/**
 * LigneFactureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LigneFactureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LigneFactureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LigneFacture');
    }
}