<?php

/**
 * LigneBordereau
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LigneBordereau extends BaseLigneBordereau
{

    public function init($libelle, $quantite, $idBordereau){
        $this->IdBordereau = $idBordereau;
        $this->Libelle = $libelle;
        $this->Quantite = $quantite;
    }
    
    public function init2($libelle, $quantite){
            $this->Libelle = $libelle;
            $this->Quantite = $quantite;
        }
}