<?php

/**
 * LigneFacture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LigneFacture extends BaseLigneFacture
{
	public function init($idArticle,$idFacture){
        $this->IdArticle = $idArticle;
        $this->IdFacture = $idFacture;
   }

}