<?php

/**
 * LigneCommande
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LigneCommande extends BaseLigneCommande
{

        public function init($idcommande, $idproduit, $quantite){
            $this->IdCommande = $idcommande;
            $this->IdProduit = $idproduit;
            $this->Quantite = $quantite;
        }
        
        public function init2($idproduit, $quantite){
            $this->IdProduit = $idproduit;
            $this->Quantite = $quantite;
        }
}