<?php

/**
 * LigneCommandeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LigneCommandeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LigneCommandeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LigneCommande');
    }
}