<?php

/**
 * LigneBordereauTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LigneBordereauTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LigneBordereauTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LigneBordereau');
    }
}