<?php

/**
 * ProduitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProduitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProduitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Produit');
    }
}