#les utilisateurs :
User:
  tableName: User
  actAs:
    Searchable:
      fields: [id,Nom, Prenom,Mail,Tel,Type]
  columns:
    Login:
      type: string(255)
      unique: true
      notnull: true
    Password:
      type: string(255)
      notnull: true
    Nom:
      type: string(255)
    Prenom:
      type: string(255)
    Mail:
      type: string(255)
    Tel:
      type: string(255)
    Type:
      type: integer

#les clients :
Client:
  tableName: Client
  actAs:
    Searchable:
      fields: [id,Nom, Prenom,Mail,Tel]
  columns:
    Nom:
      type: string(255)
    Prenom:
      type: string(255)
    Mail:
      type: string(255)
    Tel:
      type: string(255)
    Commentaire:
      type: string(255)

#les factures :
Facture:
  tableName: Facture
  actAs:
    Timestampable: 
      created:
        name: Date
      updated:
        name: DateModif
  columns:
    IdClient:
      type: integer
    IdUser:
      type: integer
      notnull: true
    IdUserModif:
      type: integer
      notnull: true
    TotalHT:
      type: float
    TotalTTC:
      type: float
  relations:
    client:
      class: Client
      local: IdClient
      foreign: id
      alias: Client # on pourra acceder à l'objet avec Facture->Client
      foreignAlias: FactureClient
    user:
      class: User
      local: IdUser
      foreign: id
      alias: User # on pourra acceder à l'objet avec Facture->Client
      foreignAlias: FactureUser
    userModif:
      class: User
      local: IdUserModif
      foreign: id
      alias: UserModif # on pourra acceder à l'objet avec Facture->Client
      foreignAlias: FactureUserModif


#les classes de produit :
Classe:
  tableName: Classe
  actAs:
    Searchable:
      fields: [Libelle]
  columns:
    Libelle:
      type: string(255)

#les Taxes
Taxe:
  tableName: Taxe
  actAs:
    Timestampable: 
      created:
        name: Date
      updated:
        name: DateModif
  columns:
     Libelle:
       type: string(255)
     Taux:
       type: float

#les produits :
Produit:
  tableName: Produit
  actAs:
    Searchable:
      fields: [id,Libelle, Conditionnement]
  columns:
    Libelle:
      type: string(255)
    PrixAT:
      type: float
    Prix:
      type: float
    Ordonnance:
      type: boolean
    Commentaire:
      type: string(255)
    Alerte:
      type: integer
    Conditionnement:
      type: string(255)
    IdClasse:
      type: integer
    IdTaxe: 
      type: integer
  relations:
    classe:
      class: Classe
      local: IdClasse
      foreign: id
      alias: Classe # on pourra acceder à l'objet avec LigneFacture->Facture
      foreignAlias: ProduitClasse
    taxe:
      class: Taxe
      local: IdTaxe
      foreign: id
      alias: Taxe # on pourra acceder à l'objet avec Produit->Taxe->taux
      foreignAlias: ProduitTaxe

#les lignes de facture :
LigneFacture:
  tableName: LigneFacture
  columns:
    IdArticle:
      type: integer
    IdFacture:
      type: integer
  relations:
    facture:
      class: Facture
      local: IdFacture
      foreign: id
      alias: Facture # on pourra acceder à l'objet avec LigneFacture->Facture
      foreignAlias: LigneFactureFacture
    article:
      class: Article
      local: IdArticle
      foreign: id
      alias: Article # on pourra acceder à l'objet avec LigneFacture->Facture
      foreignAlias: LigneFactureArticle

#les états de commande :
Etat:
  tableName: Etat
  columns:
    Libelle:
      type: string(255)

#les commandes
Commande:
  tableName: Commande
  actAs:
    Timestampable: 
      created:
        name: Date
      updated:
        name: DateModif
  columns:
    IdUser:
      type: integer
    IdUserModif:
      type: integer
    IdFournisseur:
      type: integer
    IdEtat:
      type: integer
  relations:
    user:
      class: User
      local: IdUser
      foreign: id
      onDelete: SET NULL
      alias: User # on pourra acceder à l'objet avec Facture->Client
      foreignAlias: CommandeUser
    userModif:
      class: User
      local: IdUserModif
      foreign: id
      onDelete: SET NULL
      alias: UserModif # on pourra acceder à l'objet avec Facture->Client
      foreignAlias: CommandeUserModif
    fournisseur:
      class: Fournisseur
      local: IdFournisseur
      foreign: id
      onDelete: SET NULL
      alias: Fournisseur # on pourra acceder à l'objet avec Facture->Client
      foreignAlias: CommandeUserModif
    etat:
      class: Etat
      local: IdEtat
      foreign: id
      onDelete: SET NULL
      alias: Etat # on pourra acceder à l'objet avec Facture->Client
      foreignAlias: CommandeEtat

#les Bordereaux
Bordereau:
  tableName: Bordereau
  actAs:
    Timestampable: 
      created:
        name: Date
      updated:
        name: DateModif
  columns:
    IdCommande:
      type: integer
  relations:
    commande:
      class: Commande
      local: IdCommande
      foreign: id
      onDelete: SET NULL
      alias: Commande # on pourra acceder à l'objet avec LigneFacture->Facture
      foreignAlias: BordereauCommande

#les articles :
Article:
  tableName: Article
  actAs:
    Searchable:
      fields: [id,CodeBarre]
    Timestampable: 
      created:
        name: DateAjout
      updated:
        name: DateModif
  columns:
    CodeBarre:
      type: string(255)
    DateExpiration:
      type: date
    IdProduit:
      type: integer
    IdBordereau:
      type: integer
    DateVente:
      type: date
    Commentaire:
      type: string(255)
    Panier:
      type: boolean
    Etat:
      type: string(255)
  relations:
    produit:
      class: Produit
      local: IdProduit
      foreign: id
      onDelete: SET NULL
      alias: Produit # on pourra acceder à l'objet avec LigneFacture->Facture
      foreignAlias: ArticleProduits
    bordereau:
      class: Bordereau
      local: IdBordereau
      foreign: id
      onDelete: SET NULL
      alias: Bordereau # on pourra acceder à l'objet avec Facture->Client
      foreignAlias: ArticleBordereau

#les fournisseurs :
Fournisseur:
  tableName: Fournisseur
  actAs:
    Searchable:
      fields: [id,Libelle, Adresse,Mail,Tel]
  columns:
    Libelle:
      type: string(255)
    Adresse:
      type: string(255)
    Tel:
      type: string(255)
    Mail:
      type: string(255)
    Commentaire:
      type: string(255)

#les ligne de commandes
LigneCommande:
  tableName: LigneCommande
  actAs:
    Timestampable: 
      created:
        name: Date
      updated:
        name: DateModif
  columns:
    IdCommande:
      type: integer
    IdProduit:
      type: integer
    Quantite:
      type: integer
  relations:
    commande:
      class: Commande
      local: IdCommande
      foreign: id
      onDelete: SET NULL
      alias: Commande # on pourra acceder à l'objet avec LigneFacture->Facture
      foreignAlias: LigneCommandeCommande
    produit:
      class: Produit
      local: IdProduit
      foreign: id
      onDelete: SET NULL
      alias: Produit # on pourra acceder à l'objet avec LigneFacture->Facture
      foreignAlias: LigneCommandeProduit

#les lignes Bordereaux
LigneBordereau:
  tableName: LigneBordereau
  actAs:
    Timestampable: 
      created:
        name: Date
      updated:
        name: DateModif
  columns:
    IdProduit:
      type: integer
    Quantite:
      type: integer
    IdBordereau:
      type: integer
  relations:
    bordereau:
      class: Bordereau
      local: IdBordereau
      foreign: id
      onDelete: SET NULL
      alias: Bordereau # on pourra acceder à l'objet avec LigneFacture->Facture
      foreignAlias: LigneBordereauBordereau
    produit:
        class: Produit
        local: IdProduit
        foreign: id
        onDelete: SET NULL
        alias: Produit # on pourra acceder à l'objet avec LigneFacture->Facture
        foreignAlias: LigneBordereauProduit
