<?php

/**
 * TaxeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Taxe');
    }
}